from __future__ import annotations

from typing import Protocol

from ..models import CampusSnapshot, FeedbackRecord, ScenarioResult


class CampusRepository(Protocol):
    async def load_snapshot(self) -> CampusSnapshot: ...
    async def save_scenario(self, scenario: ScenarioResult) -> None: ...
    async def list_scenarios(self, limit: int = 20) -> list[ScenarioResult]: ...
    async def save_feedback(self, feedback: FeedbackRecord) -> None: ...
    async def list_feedback(self, limit: int = 20) -> list[FeedbackRecord]: ...
    async def get_config(self, key: str) -> str | None: ...
    async def set_config(self, key: str, value: str) -> None: ...
